project:
  type: website
  resources: robots.txt

website:
  title: "Foster Full Promotion Docs"
  navbar:
    left:
      - href: index.html
        text: Home
  site-url: "https://johnfoster.pge.utexas.edu/PromotionDocs"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  echo: false

jupyter: python3



